### ISSUE TITLE
1.19 port

### ISSUE THREAD

**Issue by Steveplays28** [DM-Fabric-Ports/Create-Crystal-Clear#3]
Hey, just opening an issue for a 1.19 port.
[Create Fabric 1.19.2](https://modrinth.com/mod/create-fabric/version/0.5.0g-791) got released 2 weeks ago.

If you're busy, no worries.

**Comment by JieningYu** [comment]
will be work on soooon

**Comment by JieningYu** [comment]
just released

**Comment by Steveplays28** [comment]
Amazing, thank you so much for the great work.
